-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         eslint = {
--           settings = {
--             format = false,
--           },
--         },
--       },
--     },
--   },
-- }
